"""30-day daily plan, 90-day weekly plan and the daily agenda.

Scheduling is deterministic for a given start date, task file, status file and
holiday file. Weekends and user-maintained holidays are light days (no focus
task). One focus task per working day, chosen by earliest due date among tasks
whose dependencies are done or already scheduled on an earlier day.
"""
import csv
import datetime as dt
import json
from pathlib import Path

from badgr_funding import applicant as applicant_mod
from badgr_funding import dates, db, status

TASKS_PATH = Path("planning/tasks.json")
STATUS_PATH = Path("planning/task_status.csv")
HOLIDAYS_PATH = Path("planning/holidays_user_maintained.csv")
FAR = dt.date(9999, 12, 31)


def load_tasks(path=TASKS_PATH):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def load_status(path=STATUS_PATH):
    p = Path(path)
    if not p.exists():
        return {}
    with open(p, newline="", encoding="utf-8") as fh:
        return {r["id"]: r for r in csv.DictReader(fh)}


def load_holidays(path=HOLIDAYS_PATH):
    p = Path(path)
    if not p.exists():
        return {}
    with open(p, newline="", encoding="utf-8") as fh:
        return {dt.date.fromisoformat(r["date"]): r["name"] for r in csv.DictReader(fh) if r.get("date")}


def set_status(task_id, new_status, evidence, path=STATUS_PATH, when=None):
    rows = load_status(path)
    rows[task_id] = {"id": task_id, "status": new_status, "date": (when or dates.today()).isoformat(), "evidence": evidence or ""}
    with open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["id", "status", "date", "evidence"], lineterminator="\n")
        w.writeheader()
        for r in sorted(rows.values(), key=lambda r: r["id"]):
            w.writerow(r)


def _d(s):
    return dt.date.fromisoformat(s) if s else None


def open_tasks(tasks, statuses, sam_active):
    out = []
    for t in tasks:
        if statuses.get(t["id"], {}).get("status") in ("done", "skipped"):
            continue
        if t.get("sam_active_only") and not sam_active:
            continue
        out.append(t)
    return out


def schedule(data, start, days=30, statuses=None, holidays=None, sam_active=False):
    """Return a list of day dicts: date, light (bool), reason, focus (task or None)."""
    statuses = statuses or {}
    holidays = holidays or {}
    done = {k for k, v in statuses.items() if v.get("status") in ("done", "skipped")}
    pending = open_tasks(data["tasks"], statuses, sam_active)
    order = {t["id"]: i for i, t in enumerate(data["tasks"])}
    plan = []
    for i in range(days):
        day = start + dt.timedelta(days=i)
        light_reason = "weekend" if day.weekday() >= 5 else holidays.get(day)
        entry = {"date": day, "light": bool(light_reason), "reason": light_reason, "focus": None}
        if not light_reason:
            ready = [t for t in pending
                     if all(dep in done for dep in t.get("depends_on", []))
                     and (_d(t.get("not_before")) or dt.date.min) <= day]
            if ready:
                pick = min(ready, key=lambda t: (_d(t.get("due")) or FAR, order[t["id"]]))
                entry["focus"] = pick
                pending.remove(pick)
                done.add(pick["id"])  # dependency satisfied for later days
        plan.append(entry)
    return plan


def weekly(data, start, weeks=13, statuses=None, holidays=None, sam_active=False):
    """Group a long schedule into weeks; tasks beyond the horizon are listed as unscheduled."""
    days = schedule(data, start, weeks * 7, statuses, holidays, sam_active)
    out = []
    for w in range(weeks):
        chunk = days[w * 7:(w + 1) * 7]
        out.append({"week": w + 1, "start": chunk[0]["date"], "end": chunk[-1]["date"],
                    "tasks": [d["focus"] for d in chunk if d["focus"]]})
    scheduled = {t["id"] for wk in out for t in wk["tasks"]}
    leftover = [t for t in open_tasks(data["tasks"], statuses or {}, sam_active) if t["id"] not in scheduled]
    return out, leftover


def render_daily(data, plan):
    lines = ["# DRAFT — 30-day daily plan", f"Start {plan[0]['date'].isoformat()} (America/New_York). Generated by `python3 -m badgr_funding.cli plan`. Targets, not commitments.", "",
             "## Daily blocks (working days)"]
    lines += [f"- {b['block']} ({b['minutes']} min): {b['what']}" for b in data["daily_blocks"]]
    lines += ["", "## Schedule", "| Date | Day | Focus task | Due | Proof of done |", "|---|---|---|---|---|"]
    for d in plan:
        dow = d["date"].strftime("%a")
        if d["light"]:
            lines.append(f"| {d['date']} | {dow} | Light day ({d['reason']}): tracker update only | | |")
        elif d["focus"]:
            t = d["focus"]
            lines.append(f"| {d['date']} | {dow} | {t['title']} (~{t['effort_min']} min) | {t.get('due') or ''} | {t['evidence']} |")
        else:
            lines.append(f"| {d['date']} | {dow} | Customer work / records catch-up | | |")
    lines += ["", "## Missing inputs", "- Owner's actual weekly hours; holidays to observe (planning/holidays_user_maintained.csv)."]
    return "\n".join(lines) + "\n"


def render_weekly(data, weeks, leftover):
    lines = ["# DRAFT — 90-day weekly plan", f"Weeks from {weeks[0]['start']} (America/New_York). Generated by `python3 -m badgr_funding.cli plan`.", "",
             "## Every week"]
    lines += [f"- {w['day']}: {w['what']}" for w in data["weekly"]]
    lines += ["", "## Weeks"]
    for wk in weeks:
        items = "; ".join(t["title"] for t in wk["tasks"]) or "Customer work, records, follow-ups"
        lines.append(f"- **Week {wk['week']}** ({wk['start']} to {wk['end']}): {items}")
    if leftover:
        lines += ["", "## Not yet schedulable", *[f"- {t['title']} (waits on: {', '.join(t.get('depends_on', [])) or t.get('not_before') or 'SAM activation'})" for t in leftover]]
    lines += ["", "## Missing inputs", "- Owner review of task order and due dates."]
    return "\n".join(lines) + "\n"


def agenda(conn, data, ref=None, horizon_days=14, statuses=None, holidays=None, appl=None,
           private_inputs=Path("private/financial_inputs.csv")):
    """Build agenda sections as lists of strings."""
    ref = ref or dates.today()
    appl = appl or applicant_mod.load()
    statuses = statuses if statuses is not None else load_status()
    holidays = holidays if holidays is not None else load_holidays()
    tasks = open_tasks(data["tasks"], statuses, appl.sam_active)
    plan = schedule(data, ref, 1, statuses, holidays, appl.sam_active)[0]
    sec = {}
    if plan["light"]:
        sec["Today"] = [f"Light day ({plan['reason']}): tracker update only"]
    else:
        sec["Today"] = [f"Focus: {plan['focus']['title']} — proof: {plan['focus']['evidence']}"] if plan["focus"] else ["Focus: customer work / records catch-up"]
    sec["Overdue"] = [f"{t['title']} (due {t['due']}) — escalate: {t['escalate']}" for t in tasks
                      if t.get("due") and _d(t["due"]) < ref]
    soon = []
    for t in tasks:
        if t.get("due") and 0 <= (_d(t["due"]) - ref).days <= horizon_days:
            soon.append((_d(t["due"]), f"task: {t['title']}"))
    for o in db.all_opportunities(conn):
        crit = db.criteria(conn, o["id"])
        if status.archive_reason(o, crit):
            continue
        for field, label in (("deadline_date", "deadline"), ("followup_date", "follow-up"), ("revisit_date", "revisit")):
            when = _d(o[field])
            if when and 0 <= (when - ref).days <= horizon_days:
                extra = ""
                if field == "deadline_date":
                    extra = f" [{dates.deadline_display(o['deadline_date'], o['deadline_time'], o['deadline_tz'], o['rolling'])}]"
                soon.append((when, f"{label}: {o['program']}{extra}"))
    sec[f"Due in next {horizon_days} days"] = [f"{w.isoformat()} {txt}" for w, txt in sorted(soon)]
    stale = [f"{o['program']} (last checked {(o['source_checked_at'] or 'never')[:10]})" for o in db.all_opportunities(conn)
             if not status.archive_reason(o, []) and dates.is_stale(o["source_checked_at"], status.MAX_SOURCE_AGE_DAYS, ref)]
    sec["Stale sources (>30 days or never checked)"] = stale
    missing = []
    if not Path(private_inputs).exists():
        missing.append("private/financial_inputs.csv not created (cash flow and repayment blocked)")
    else:
        with open(private_inputs, newline="", encoding="utf-8-sig") as fh:
            blank = [r["field"] for r in csv.DictReader(fh) if not r["value"].strip()
                     and r["field"] in ("cash_on_hand", "monthly_business_expenses", "existing_debt_payments", "2026_ytd_revenue", "2026_ytd_through")]
        if blank:
            missing.append("financial inputs still blank: " + ", ".join(blank))
    sec["Missing inputs"] = missing
    sec["Open advisor/lender questions"] = [t["title"] for t in tasks if t["category"] == "advisor"]
    sec["SAM"] = (["SAM Active: activation tasks added to the plan"] if appl.sam_active
                  else ["SAM still pending: check status (Wednesdays)"])
    return sec
